version: "3.3"

services:
  wordpress:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./bedrock:/var/www/html
      - ./sage-theme:/sage-theme
      - ./nginx/default:/etc/nginx/sites-available/default
    ports:
      - "8080:80"
    restart: always

  db:
    image: mariadb:latest
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: wordpress
      MARIADB_USER: admin
      MARIADB_PASSWORD: password

#  nginx:
#    image: nginx:1.23
#    depends_on:
#      - wordpress
#    ports:
#      - "80:80"
#    volumes:
#      - ./bedrock:/app
#      - ./default.conf:/etc/nginx/conf.d/default.conf
#    restart: always

volumes:
  db_data: { }